### ISSUE TITLE
DNS NXDomain Rust unwrap panic: device.auth.xboxlive.com

### ISSUE THREAD

**Issue by Originalimoc** [unknownskl/xbox-xcloud-client#1000]
On a wacky DNS server sometimes you'll randomly get NXDOMAIN for no good reason. Even systemd-resolve/127.0.0.53 may do this. So in Rust code this part should change to retry or something better than unwrap panic that requires a full restart.

**Comment by unknownskl** [comment]
I think this is fixed by switching to the native typescript library of xal-node. If it still happens then the DNS server should be fixed in my opinion because that's where the problem resides.

**Comment by Originalimoc** [comment]
I guess so as similar issue didn't happen again.
