### ISSUE TITLE
(Steam Deck) Timeout Error

### ISSUE THREAD

**Issue by IVlrBlue** [unknownskl/xbox-xcloud-client#1011]
![Steam Deck Screen Shot](https://github.com/unknownskl/greenlight/assets/50670944/81a58e43-9eb3-4d89-bca5-7a2489a47096)

Keep getting this error when trying to start stream. Reset Xbox and steam deck. Also tried reinstalling greenlight.

**Comment by HollowEvil** [comment]
same error on pc too

**Comment by ricflairandy** [comment]
yep, same here. Somthing must have changed?.

**Comment by HollowEvil** [comment]
> yep, same here. Somthing must have changed?.

i reboot xbox and now all work fine, try too

**Comment by IVlrBlue** [comment]
> > yep, same here. Somthing must have changed?.
> 
> i reboot xbox and now all work fine, try too

Usually resetting my Mac address accomplishes this, but I tried hard resetting the standard way and it seemed to work.

Thanks!
