### ISSUE TITLE
Inputs not working on Fortnite 

### ISSUE THREAD

**Issue by Nolimitzain** [unknownskl/xbox-xcloud-client#1027]
It seems to only be a problem with Fortnite but my button inputs do not register when streaming

**Comment by Kobi-Blade** [comment]
This is a known issue with Xbox, nothing Greenlight can do to fix.

When using remote play, the Controller keybinds do not work correctly, report the issue to Epic and Microsoft, as many have done thus far.

**Comment by Nolimitzain** [comment]
I figured out a fix, Bluetooth connected controller to my computer and it
works now

**Comment by unknownskl** [comment]
Closing issue as the issue has been fixed in your case
