### ISSUE TITLE
winget Package

### ISSUE THREAD

**Issue by ksharizard** [unknownskl/xbox-xcloud-client#1034]
Adding greenlight as a winget package would make it easy and secure to install and manage on windows.

Edit:
Looks like a [package request](https://github.com/microsoft/winget-pkgs/pull/137662) was sent on the winget repo but it has been blocked due to a winget issue.

**Comment by Movisivi** [comment]
This is a dumb request. Why would you need this when the Xbox App is superior

**Comment by ksharizard** [comment]
> This is a dumb request. Why would you need this when the Xbox App is superior. Only reason we use this on Linux is because its the closest we can get to the Xbox app experience

I like greenlight because I don't want the extra features the xbox app has and I would rather have an open source solution just to stream my xbox to my windows device.

**Comment by ksharizard** [comment]
Fixed by https://github.com/microsoft/winget-pkgs/pull/137662
