### ISSUE TITLE
Sonoma 14.2 Introduces jitter

### ISSUE THREAD

**Issue by Disorderly007** [unknownskl/xbox-xcloud-client#1075]
After Sonmoa upgrade to 14.2 i'm getting constant jitter 

![image](https://github.com/unknownskl/greenlight/assets/68718052/0ad5e7eb-c4c3-4c8c-bb80-7a4312be3112)

**Comment by JeffTHX** [comment]
Hello, I am experiencing this exact same issue. Xbox is on Ethernet. Wifi is ac, excellent signal.  16" M1 MacBook Pro (2021) on Sonoma.

**Comment by Disorderly007** [comment]
I actually found that for me the problem was introduced by turning on a 3rd monitor after the Mac had booted if i rebooted with he third monitor already on it eliminated the Jitter, if your running external monitors  that might be the cause

**Comment by JeffTHX** [comment]
I do have 2 monitors that I sometimes dock to on this machine (making a total of 3 including laptop LCD). I'll try a reboot now. Note however I'm also getting this issue on another machine, my intel mac. Which is only ever connected to 1 external monitor.

Could it be an external monitor issue perhaps? Rebooting now.

**Comment by JeffTHX** [comment]
Ok rebooted the laptop. So this is a fresh boot untainted by previous external monitor connections. This fixed it!

Thank you. Hope the bug can be fixed.

Now am going to try to try the Intel Mac.  (update: ok the Intel Mac his a bit of random jitter but no where near the cyclical jitter I was getting on the m1 prior to reboot).

So it definitely has something to do with external monitors.

**Comment by JeffTHX** [comment]
Disorderly, would you mind setting this issue as open? Else I can transfer to a new issue.

**Comment by Disorderly007** [comment]
I think it is actually an OS issue, as when the jitter was happening i noticed that ping's to my router were also spiking which has nothing to do with greenlight

**Comment by Disorderly007** [comment]
Further testing on my side reveals the issue to be Continuity if i have my running continuity it introduces a consistent  Ping increase and hangs around until a reboot

**Comment by JeffTHX** [comment]
How are you disabling Continuity? I have an iphone as well.

Or are you saying just make sure not to use Continuity Camera/Microphone
after fresh reboot?

**Comment by Disorderly007** [comment]
Sorry I meant universal control, but yeah after the reboot make sure not to use UC

**Comment by JeffTHX** [comment]
Okay thanks a lot. A simple search of “Mac AWDL Sonoma bug” is yielding
tons of results, so the issue is widespread.

Definitely an OS bug not Greenlight. Thanks for steering me in the right
direction.
