### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by TheDarkPinecone** [unknownskl/xbox-xcloud-client#1085]
I installed an older version via a youtube link and tried to install the newer version ,which has a bug fix for gamepad connection. And it won't show as a open able software. 
<img width="704" alt="Screenshot 2023-12-25 at 10 07 05 PM" src="https://github.com/unknownskl/greenlight/assets/152344405/b2d86b99-eb6c-44ba-9052-4b16bddcb949">
<img width="746" alt="Screenshot 2023-12-25 at 10 07 17 PM" src="https://github.com/unknownskl/greenlight/assets/152344405/0390d6c4-e9a6-4b29-84dc-6e51b120ddcc">

**Comment by unknownskl** [comment]
It looks like you have downloaded the source code. Check the releases page for the .dmg file (as you are running on a Mac).

**Comment by TheDarkPinecone** [comment]
Thank you so much!
