### ISSUE TITLE
Timing out as of today - unable to stream

### ISSUE THREAD

**Issue by pevsfreedom** [unknownskl/xbox-xcloud-client#1095]
Trying to stream today and it's apparently timing out, not letting me able. It's turning the xbox on but not streaming to the laptop.

<img width="278" alt="Screenshot 2024-01-09 at 11 53 01 AM" src="https://github.com/unknownskl/greenlight/assets/151674984/adb2f0bf-a142-4e35-b2b9-0dda996f6a75">

**Comment by pevsfreedom** [comment]
Hard reset on the XBOX fixed the issue.

**Comment by riddhimanrana** [comment]
yeah, it fixed it for me
pls react w/heart to this comment I need a git badge
