### ISSUE TITLE
High Jitter. 2021 16" MacBook Pro M1 on Sonoma.

### ISSUE THREAD

**Issue by JeffTHX** [unknownskl/xbox-xcloud-client#1103]
### Describe the bug

See screenshot for the jitter. Video is choppy not smooth. Perfect network connectivity with Xbox on ethernet and wifi is ac.
<img width="1728" alt="Screenshot 2024-01-15 at 5 00 17 PM" src="https://github.com/unknownskl/greenlight/assets/77946261/3a469dde-a2ea-4748-a83f-992731c72677">

### Environment

```markdown
- OS: 
- Device: 
- Greenlight version:
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by JeffTHX** [comment]
Started a new issue because this one was closed as unplanned:  https://github.com/unknownskl/greenlight/issues/1075
But I have since been commenting on that one with the original author. See his workaround (reboot with no external monitors). Bug still needs to be fixed.

**Comment by unknownskl** [comment]
I think this is more of an OS problem then it is in the program / electron. Closing the issue
