### ISSUE TITLE
Every time I stream it gives an error.

### ISSUE THREAD

**Issue by uhjeristic** [unknownskl/xbox-xcloud-client#1106]
### Describe the bug

When I stream it says Stream error result: Failed
Details: [WNSError] Xccs : ErrorCallingWNS : Send command failed : State WaitingForServerToRegister

### Environment

```markdown
- OS: 15.7
- Device: iMac
- Greenlight version: 2.01
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Try to restart the console. This has been reported a lot lately and unfortunately there is no way to prevent this error as it happens on the normal xbox app too. Sometimes the xbox loses the connection and needs to be turned on manually before it connects to the xbox network. (Mostly happen after updates or when the user is signed off overnight)
