### ISSUE TITLE
[BUG] Stream not connecting

### ISSUE THREAD

**Issue by Painthetownred154** [unknownskl/xbox-xcloud-client#1110]
### Describe the bug

When I tried to use remote play from my Xbox to my steam deck, green light would load for around five seconds before showing this error: 
![IMG_3330](https://github.com/unknownskl/greenlight/assets/157324464/85bb9750-0f70-427f-a99f-3ad3d40d5eba)

I’ve tried using different versions, uninstalling and reinstalling it but nothing so far has worked.

### Environment

```markdown
- OS: SteamOS
- Device: Steam Deck
- Greenlight version: 
2.0.1
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Try to restart the console. This has been reported a lot lately and unfortunately there is no way to prevent this error as it happens on the normal xbox app too. Sometimes the xbox loses the connection and needs to be turned on manually before it connects to the xbox network. (Mostly happen after updates or when the user is signed off overnight)
