### ISSUE TITLE
PS4/PS5 wired controllers no longer working

### ISSUE THREAD

**Issue by alexwinston** [unknownskl/xbox-xcloud-client#1117]
### Describe the bug

With release 2.1.0 wired Playstation controllers are no longer working.  They are detected in the Settings section but do not actually work once the stream is connected to the console.  They worked in the last release, 2.0.1.  I checked the logs and don't see anything unusual that would suggest they aren't working.

### To Reproduce

Plug in a wired PS4/PS5 controller.  Go to the Settings and it will be listed.  Start a stream and the input is not received from the controller.

### Expected behavior

Controller should send inputs to the Xbox stream.

### Environment

```markdown
- OS: macOS 14.1.2
- Device: MacBook Pro A2
- Greenlight version: 2.1.0
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by Cliff2103** [comment]
Same for Xbox controllers

**Comment by unknownskl** [comment]
Thanks for the report! The issue seems to be in the old gamepad driver. As a workaround you can enable the new gamepad driver in Settings -> Input. 

I will push a new update in the coming week.

**Comment by Cliff2103** [comment]
> Thanks for the report! The issue seems to be in the old gamepad driver. As a workaround you can enable the new gamepad driver in Settings -> Input.
> 
> I will push a new update in the coming week.

Thanks! The update looks real good though :)

**Comment by unknownskl** [comment]
Thanks! Version 2.1.1 has been released and should contain a fix for the controller. Please test it and let me know if it fixes the problem on your side too.

**Comment by Cliff2103** [comment]
It works for me, thanks a lot!

**Comment by Shusanta** [comment]
still broken

**Comment by unknownaccount11** [comment]
Not sure if I'd have to create another issue for this or if it'd be worth fixing before V3 but I'm positive this has cropped up again, at least trying on Steam Deck build (Flatpak through Discover store) - my PS4 controller shows up under gamepads in Input but no input happens in stream. Have tried with Wii U Pro Controller and it shows up + works fine.
