### ISSUE TITLE
[Bug] Stream Wont Connect

### ISSUE THREAD

**Issue by Micah0220** [unknownskl/xbox-xcloud-client#1124]
### Describe the bug

restarted console multiple times. any fixes to this bug?
![image](https://github.com/unknownskl/greenlight/assets/158230913/86f57690-643c-4681-a6cc-8aa93e756464)

### Environment

```markdown
- OS: 
- Device: 
- Greenlight version:
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Please hard reset your console. This is due to a problem between the Xbox and the Xbox servers.

This bug had reported many times. Next time please check the closed issues before opening new ones.
