### ISSUE TITLE
New macOS icon

### ISSUE THREAD

**Issue by el2zay** [unknownskl/xbox-xcloud-client#1127]
### Describe the feature

I'm proposing this icon because the one on macOS is far too big for the dock and doesn't fit in with the Big Sur style. 

### Describe the use case

Here's a before-and-after rendering of the app in the dock. 
![image](https://github.com/unknownskl/greenlight/assets/79168733/e9798c1e-267d-4e96-9667-d3381c83f40b)

### Additional information

Here is a list of changes:

- Rectangle size: 412x412
- Cloud size: 380x380
- Linear Gradient: RGB 17,17,17 to RGB 61,63,67

Made with Figma
[icon.icns.zip](https://github.com/unknownskl/greenlight/files/14157024/icon.icns.zip)

**Comment by unknownskl** [comment]
Thanks! I will update the icons. Looks way better indeed :)
