### ISSUE TITLE
[Bug] Stuck Loading 

### ISSUE THREAD

**Issue by Shrimbop** [unknownskl/xbox-xcloud-client#1145]
### Describe the bug

Hey there,

Greenlight was working fine until yesterday where now I'm stuck on the loading screen. 

<img width="870" alt="Screenshot 2024-02-17 at 12 32 17 PM" src="https://github.com/unknownskl/greenlight/assets/67430754/13244d87-80b0-4ac2-8cb1-5b87f518b586">

Any ideas? 

### Environment

```markdown
- OS: 
- Device: 
- Greenlight version:
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by Dragon-23** [comment]
It seems to be a login issue I basically put this in DEBUG="greenlight:*" /Applications/Greenlight.app/Contents/MacOS/Greenlight and then cleared data and logged back which caused it to be stuck on a login loop and now I get this error "[SigninBlockedByPasswordPrompt] Agent : -2138701818 :  : State WaitingForServerToRegister". So I think the login system is to blame.

**Comment by Dragon-23** [comment]
Edit: I resetted my password and forgot to do it on my xbox :P, so just add DEBUG="greenlight:*" /Applications/Greenlight.app/Contents/MacOS/Greenlight 

It should work 👍

**Comment by Shrimbop** [comment]
That solved it, thank you.
