### ISSUE TITLE
[Bug] streaming cannot start with WNSERROR

### ISSUE THREAD

**Issue by poorest1212** [unknownskl/xbox-xcloud-client#1156]
### Describe the bug

I can remotely stream to my home console via xbox app on iPhone. But greelight give me WNSERROR report every time I start streaming, any idea what the error is and how to deal with it?
<img width="1392" alt="截屏2024-03-04 00 32 10" src="https://github.com/unknownskl/greenlight/assets/13671130/ffcb87a8-eafa-4583-bb8d-7c8b5cb243b9">

### Environment

```markdown
- OS: 
- Device: 
- Greenlight version:
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Hard reboot your console and try it again later. The newer version of Greenlight has a better clear error message which suggests to hard reboot the console.
