### ISSUE TITLE
[Bug]  macOS keeps asking for Microphone Access

### ISSUE THREAD

**Issue by rosenkrieger** [unknownskl/xbox-xcloud-client#1169]
### Describe the bug

Using Version 2.2.0 (2.2.0) on macOS 14.2.1 (23C71) - when I start the app I get asked to give microphone access, which I grant. If I close the app and start it again it will ask again for mic access. 

I have checked macOS system settings / privacy and Greenlight DOES have it set to allow mic access. But it still keeps on asking.

### To Reproduce

1. Start App
2. Grant Microphone access
3. Close App
4. Start App
5. Grant microphone access yet again...

### Expected behavior

It should only ask once for mic access .

### Environment

```markdown
- OS: macoS Sonoma 14.2.1 (23C71)
- Device: iMac M1 
- Greenlight version: Version 2.2.0 (2.2.0)
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by Yucky-XS** [comment]
Same issue here too, different OS. Running into the Microphone access infinite loop prompt.

- OS: macoS Ventura 13.6.3 (22G436)
- Device: Macbook Air M1 
- Greenlight version: Version 2.2.0 (2.2.0)

<img width="1283" alt="CleanShot 2024-03-07 at 21 18 56@2x" src="https://github.com/unknownskl/greenlight/assets/70144007/f8aa5b1d-671c-4a5e-a7f5-3f2497a144bc">

**Comment by joe-heaton** [comment]
> Same issue here too, different OS. Running into the Microphone access infinite loop prompt.
> 
> * OS: macoS Ventura 13.6.3 (22G436)
> * Device: Macbook Air M1
> * Greenlight version: Version 2.2.0 (2.2.0)
> 
> <img alt="CleanShot 2024-03-07 at 21 18 56@2x" width="1283" src="https://private-user-images.githubusercontent.com/70144007/311025259-f8aa5b1d-671c-4a5e-a7f5-3f2497a144bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTE2NTcsIm5iZiI6MTcwOTg1MTM1NywicGF0aCI6Ii83MDE0NDAwNy8zMTEwMjUyNTktZjhhYTViMWQtNjcxYy00YTVlLWE3ZjUtM2YyNDk3YTE0NGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIyNDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OGRiNDMyYzczOTM4OTcxZWQyMjUzNDBhYTU0MDA1NDYxOGQyOTZjNmRhY2NlZDBlYWQyZTNkOTU2ZDY5OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0IC5cynqjNAiz3ghca1oZgfI7IyZnkBX_l2FmJ_82Zs">

Exactly the same for me.

**Comment by gillham** [comment]
Does v2.2.0 actually work after allowing the microphone access?  

I'm running Sonoma 14.4 on a new M3 Max and the window shows the green spinning thing like in the screenshot above. I gave up after a minute or two.  With v2.1.1 it shows my Xbox and I can start / stop the stream.  It seems to behave "normal" like when I've run on Linux.

**Comment by Trailingslashes** [comment]
@gillham, no it appears it doesn't.

**Comment by Trailingslashes** [comment]
Version 2.1.1 opens no problem.

**Comment by unknownskl** [comment]
Bug has been identified. The 'fix' was not properly tested from my side so i am going to revert the 'fix'. A new update should be available soon

**Comment by unknownskl** [comment]
Update v2.2.1 removes the annoying microphone popup. Keep in mind that there is still a bug which spams a request window when you enable the microphone. This bug will be solved at a later point.

**Comment by rosenkrieger** [comment]
Just installed Version 2.2.1 (2.2.1) and it is working fine now for me. Thank you!

**Comment by unknownskl** [comment]
Awesome, thanks for letting know. I will close this issue as there is another open issue for the mic permissions in #1078
