### ISSUE TITLE
[Bug] Console Stream doesn't work in another network

### ISSUE THREAD

**Issue by lucasrossi95** [unknownskl/xbox-xcloud-client#1177]
### Describe the bug

Hi! The app works flawlessly when i'm in the same network as my Xbox Series X, but when i'm on another network it just shows a black screen with the message "Connecting to console...".

I read a couple solved bugs that mentioned configuring the router, but that shouldn't be necessary since I tried the following alternatives using another network and both of those work:
- The Xbox app on my iPhone.
- The Xbox app from Parallels with Windows 11 on my Mac.
Both options worked using the same outside network, but when I try with Greenlight it doesn't work.

If those 2 options work without configuring the router, my guess is something is not letting Greenlight connect via an outside network. Needless to say, Greenlight is a much better option, so i'd love to use it instead of those other 2 options above.

### Environment

```markdown
- OS: MacOS Sonoma 14.1.1
- Device: Macbook Pro M1
- Greenlight version: 2.2.1
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Port 9002 needs to be forwarded in your router. Can you try that and then try to start a stream from a remote network?

The official Xbox app uses Teredo to connect remotely which Greenlight does not support and thus port 9002 needs to be forwarded.

**Comment by lucasrossi95** [comment]
Sorry for my ignorance, but this is what my modem shows when I click on the port forwarding option. Do you know what should I put here?

<img width="653" alt="image" src="https://github.com/unknownskl/greenlight/assets/18254392/fb382480-c33a-4ec8-96af-9060e4e01f61">

Maybe that helps other non-technical people like me.

**Comment by unknownskl** [comment]
Try these settings:
Common service: Other
Service name: can be anything you want, xbox for example
Service type: tcp/udp
Ipv4 address: fill in your Xbox ip address. Can be found in the Xbox settings
Internal port: 9002
Start port: 9002
End port: 9002

**Comment by lucasrossi95** [comment]
Thank you! Will try that and come back to tell you if that worked :)

**Comment by v-127** [comment]
I did open the port correctly but still won't connect, this is the error it gives in terminal 

`[1301:0317/022750.277240:ERROR:vt_video_encode_accelerator_mac.cc(953)] Call NotifyErrorStatus(): code=7, message=VTCompressionSessionCreate failed: Error Domain=NSOSStatusErrorDomain Code=-12902 "(null)"`

And this error on webUI `Stream error result: Failed
Details: [AgentCommandError] Agent : -2147019873 : Timed out waiting for Cloud Streaming Service to be ready. : State ServerStartStreamingV2CommandSent`

**Comment by lucasrossi95** [comment]
> Try these settings: Common service: Other Service name: can be anything you want, xbox for example Service type: tcp/udp Ipv4 address: fill in your Xbox ip address. Can be found in the Xbox settings Internal port: 9002 Start port: 9002 End port: 9002

That worked! Thank you :)
