### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [unknownskl/xbox-xcloud-client#1186]
### Describe the feature

Verify the flatpak on Flathub

### Describe the use case

This will let people who find greenlight through Flathub know it is official

### Additional information

Here is a link to Flathub's verification documentation for developers https://docs.flathub.org/docs/for-app-authors/verification

**Comment by unknownskl** [comment]
I've submitted a verification review so it should hopefully soon be resolved. Thanks for reporting!

**Comment by unknownskl** [comment]
App has been verified!
