### ISSUE TITLE
[Bug] Login fails with a 403 error for countries without xCloud support

### ISSUE THREAD

**Issue by unknownskl** [unknownskl/xbox-xcloud-client#1193]
### Describe the bug

While logging in the application returns a 403 error in countries without xCloud support.

### To Reproduce

Open Greenlight in a country which does not support xCloud.

### Expected behavior

To login properly

### Environment

```markdown
- OS: all
- Device: all
- Greenlight version: 2.3.0
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Issue has been identified and is caused because the authentication method was updated and (mistakenly) assumed that every user should be able to retrieve an xCloud token (either for GPU / GPUF2P).

A new update is expected to arrive in a couple hours which should fix this issue.

**Comment by unknownskl** [comment]
New release v2.3.1 has been released. Flathub release should appear in a couple hours.

**Comment by chandeeps** [comment]
Just want to say thank you the tool is now working as usually. You are amazing. Haven't tested completely but i am sure it will keep getting better

**Comment by jacknight** [comment]
Back up and running in Cyprus. Brilliant work.

**Comment by unknownskl** [comment]
Awesome, good to hear it also fixed the issue on your sides. Thanks for letting know!

**Comment by 0p3r410nT** [comment]
cannot access any games other than Fortnite, not sure if this is a location error or not please assist me so I can keep using this service
