### ISSUE TITLE
[FEATURE] web version of greenlight

### ISSUE THREAD

**Issue by skibidirizzler0** [unknownskl/xbox-xcloud-client#1196]
### Describe the feature

a website would be cool since theres a lot of different features compared to the original xbox cloud site (ex. keyboard and mouse input, custom bitrate, forced regions)

**Comment by gaberilde** [comment]
You do have a webui in later builds already
https://github.com/unknownskl/greenlight/issues/673
It can only run from your computer without extra setup currently tho

**Comment by unknownskl** [comment]
what @gaberilde said, The feature is already implemented, however i do recognise that a lot of options are hidden due to lack of documentation. Will try to improve that in the next 1/2 months.
