### ISSUE TITLE
[Bug] startStream error: '/v5/sessions/home/play' got 503 code

### ISSUE THREAD

**Issue by Geocld** [unknownskl/xbox-xcloud-client#1210]
### Describe the bug

I have been running Greenlight in dev mode and have been able to stream locally to my Xbox without any issues. However, recently I encountered a network request error for '/v5/sessions/home/play'. I'm not sure if this is just happening to me or if there's an issue with Microsoft's servers.

![image](https://github.com/unknownskl/greenlight/assets/13679095/e972981e-7c6c-4951-9f49-acba88c297b1)
![image](https://github.com/unknownskl/greenlight/assets/13679095/ccbd21c1-1f9a-4a45-8f67-d3cd7911c562)

### To Reproduce

1. open greenlight project
2. run `npm run dev`
3. login account if necessary
4. start stream will see this log and error modal.

### Expected behavior

Run stream successfully.

### Environment

```markdown
- OS: windows
- Device: PC
- Greenlight version: 2.2.1
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
I think this is a server sided error. Just tried to start a stream and it works for me. Can you try it again?
If it still fails then it might have something to do with the region. The logs currently dont output the used region

**Comment by Geocld** [comment]
> I think this is a server sided error. Just tried to start a stream and it works for me. Can you try it again? If it still fails then it might have something to do with the region. The logs currently dont output the used region

I know Microsoft has only opened up cloud gaming services to certain regions. Do you know the specific regional restrictions policy? Can these restrictions be bypassed by adding certain fields to the request header? Also, what logs in Greenlight can show the current region? I'm studying the source code and workings of Greenlight, and I hope to get your help. Thank you.

**Comment by Zhaumbie** [comment]
Had the same error. Updating to v2.3.1 fixed for me

**Comment by unknownskl** [comment]
> Had the same error. Updating to v2.3.1 fixed for me

Good catch! v2.2.1 has a bug which prevents the application from starting new streams and this was fixed in version v2.3.0 and v.2.3.1 respectively. Please update your version and try again.

**Comment by Geocld** [comment]
v2.3.1 fixed, good job!
