### ISSUE TITLE
How can I use Xbox streaming on the switch[FEATURE] 

### ISSUE THREAD

**Issue by ouni666** [unknownskl/xbox-xcloud-client#1214]
### Describe the feature

How can I use Xbox streaming on the switch

### Describe the use case

How can I use Xbox streaming on the switch

### Additional information

How can I use Xbox streaming on the switch

**Comment by unknownskl** [comment]
This project only aims Windows, Linux and macOS as targets. The Nintendo switch is not supported and won't be added anytime soon as it doesn't have a proper browser
