### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ASHCHH123** [unknownskl/xbox-xcloud-client#1232]
### Describe the bug

THE APP IS NOT OPENING AT ALL. I TRIED REINSTALLING IT AND EVERYTHING. IT STILL WONT WORK

### Environment

```markdown
- OS: 
- Device: 
- Greenlight version:
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Please fill out the OS and attach a screenshot please. Low effort bug reports will be closed immediately
