### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Undreamthook03** [unknownskl/xbox-xcloud-client#1250]
### Describe the bug

Upon opening the app on my OneXPlayer 2 Pro 8840U (windows 11), I get the following error immediately after boot. 
![image](https://github.com/unknownskl/greenlight/assets/172917557/e83fcec1-967a-4f89-a7db-a82e5c331cac)

### To Reproduce

Click on app and error pops up almost immediately. 

### Environment

```markdown
- OS: Windows 11
- Device: OneXPlayer 2 Pro 8840U
- Greenlight version: v2.3.1
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Can you check if the time and date are set correctly? This usually happens when the time is off for more then 5 minutes.

**Comment by Undreamthook03** [comment]
The time and date on the device or the app? I don’t see an option to change this on the app…

**Comment by unknownskl** [comment]
No, the time from windows. The apps takes over the time automatically

**Comment by Undreamthook03** [comment]
Ah! Yes, it was off by 5 minutes. That fixed it! Thanks
