### ISSUE TITLE
Display does not update

### ISSUE THREAD

**Issue by ReenigneArcher** [unknownskl/xbox-xcloud-client#127]
When I connect to the Xbox for xbox home streaming, I can see the dashboard; however moving around with the d-pad does nothing.

I can hear the sounds that the selected item is being changed, but again cannot see any updates on the screen.

I am using:
-Windows 11 (also had the problem on Windows 10)
-Version 1.1.0 (I tried 1.2.0 beta1 also but couldn't find where to connect to my Xbox)
-Xbox One X

**Comment by sontopo** [comment]
Same with Mac and Windows.

**Comment by unknownskl** [comment]
Sometimes this happens until you restart the Xbox. Can you try to restart the Xbox and see if that helps?
