### ISSUE TITLE
after loggin... just see blank 

### ISSUE THREAD

**Issue by atlightsun** [unknownskl/xbox-xcloud-client#128]
after loggin... just see blank 

Issues checking in progress...
No issues found.
web tokens set
Requesting xHome and xCloud tokens..
- Error while retrieving xCloud token
  statuscode: 403
  body: {"code":"OfferingAccessDenied","statusCode":403,"message":""}
xhome tokens set

**Comment by atlightsun** [comment]
after logout... none cookies
After the first successful login, there is a blank. It can be displayed normally only after refreshing again

**Comment by unknownskl** [comment]
The login can take a long time. The new 1.2.0-beta2 should improve the ux of the login flow. Please try this version and let me know if it works: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.2.0-beta2
