### ISSUE TITLE
[Bug] xbox controller not working on Mac OS Sequoia

### ISSUE THREAD

**Issue by bybymax** [unknownskl/xbox-xcloud-client#1286]
### Describe the bug

Hi ! Thank you so much fir your work ! I've been using Greenlight on a daily basis without any problem for a year now. Though, I've just installed the beta version for Mac OS Sequoia and ever since the installation, the xbox controller is not working anymore, whether using a cable or through bluetooth. The controller is functional as I can play using online cloud gaming. 
I know it's been my decision to move to a beta version of the OS, and I'm not here to complain at all. But if you have the time and the possibility to fix that before the final release of Sequoia, that'd be great ! 
Thanks again for that great software you've developed ! 

Best regards,

Bybymax

### To Reproduce

1. open Greenlight
2. Launch a session
3. Connect a controller (I've tried to plug before opening greenlight, or after, without any change)
4. see if the controller is functional

### Expected behavior

I expected the controller to work on that version of MacOS, like it worked before the update.

### Environment

```markdown
- OS: MacOS Sequoia
- Device: Imac M1
- Greenlight version: Version 2.3.1 (2.3.1)
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by jbtule** [comment]
@bybymax Just FYI, I was coming here looking for another issue, but I saw this, and wanted to let you, I'm using 15.0 Public Beta (24A5309E) with my xbox controller and and MacBook Pro - M1 Pro, and Greenight 2.3.1 and I have had no issues with my Xbox Wireless Controller over Bluetooth, I used it last night even. 

```
  Xbox Wireless Controller:
  Vendor ID:	0x045E
  Product ID:	0x0B13
  Battery Level:	100%
  Firmware Version:	5.13.3143.0
  Minor Type:	Gamepad
  Services:	0x400000 < BLE >
```

**Comment by bybymax** [comment]
Hi ! thx a lot ! i reset my controller and it works using BT !
