### ISSUE TITLE
No Home Streaming in 1.2.0 beta

### ISSUE THREAD

**Issue by ReenigneArcher** [unknownskl/xbox-xcloud-client#129]
When opening 1.2.0 beta I do not get any option to connect to my console.

**1.2.0 Beta**
![image](https://user-images.githubusercontent.com/42013603/148622140-8c5e4b49-3db7-406f-b8a9-d51dca8f5630.png)

**1.1.0**
![image](https://user-images.githubusercontent.com/42013603/148622127-c09eadf3-b1c4-4f8e-9158-f8df3ba3310e.png)

**Comment by unknownskl** [comment]
This should be fixed in 1.2.0-beta2. Please try and let me know if it works for you: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.2.0-beta2

**Comment by ReenigneArcher** [comment]
> This should be fixed in 1.2.0-beta2. Please try and let me know if it works for you: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.2.0-beta2

It works, thank you!
