### ISSUE TITLE
[FEATURE] Customizable Key-Binding

### ISSUE THREAD

**Issue by Mcrich23** [unknownskl/xbox-xcloud-client#1346]
### Describe the feature

Settings page to change the keybinding.

### Describe the use case

For those where the keybinds aren't intuitive.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the input settings page to allow users to change and save keybindings. This includes updating the UI to display current keybindings, adding input fields for new keybindings, and implementing the logic to save the changes.

You can review changes in this commit: https://github.com/mnmnk43434/unknownskl-greenlight-1346/commit/2c7fd7890dd082c667c4dbfaa6cc4fe1e2980911.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Mcrich23** [comment]
@mnmnk43434 Thank you. I found this, after submitting this. I wonder if it's possible to make it possible to bind `escape` to `b`
