### ISSUE TITLE
Add Apple silicon build

### ISSUE THREAD

**Issue by Roei-Bracha** [unknownskl/xbox-xcloud-client#139]
I am really like this project and its the only way right now to stream xbox to Macbooks
my Macbook is using the apple m1 processor so I have to run the current build with "Rosetta" which damage the performance

Electron and Electron forge already support apple m1 processors
only need to add it to the build script

https://www.electronjs.org/blog/apple-silicon

**Comment by TheWorldlyGamer** [comment]
Yes absolutely. I'm currently using an M1 Mac and adding Apple Silicon would really help with my battery life and performance!

**Comment by unknownskl** [comment]
v1.2.0-beta4 should have support for Apple Silicon now. Please try it and let me know if it works as expected :)
