### ISSUE TITLE
need a option to change connection url 

### ISSUE THREAD

**Issue by ricardo-sanches** [unknownskl/xbox-xcloud-client#140]
Im from brazil and get connected on US servers so i get so much lag, can you add a option to change the server connection?

**Comment by unknownskl** [comment]
Good idea. Will add it in the new version when i have time

**Comment by unknownskl** [comment]
Please try the new beta2 release and let me know if this works for you: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.2.0-beta2

**Comment by unknownskl** [comment]
Thanks, it seems like the endpoints got updated. Will take a look in a couple days.

**Comment by unknownskl** [comment]
v1.2.0-beta4 has the updated regions list. Should fix this bug
