### ISSUE TITLE
[SteamOS] Not possible to enter code in 2fa

### ISSUE THREAD

**Issue by ghostekpl** [unknownskl/xbox-xcloud-client#237]
I have a microsoft account with 2fa enabled. I can enter username and login but 2fa code cannot be entered in any way. Only the [A-Z] keys can be used, but the numeric keys do not work. The same is true if you choose other forms of login such as phone. You cannot enter the last digits of the phone number. Tested on SteamOS

**Comment by unknownskl** [comment]
This seems to be a bug with SteamOS indeed. As i dont have a Steam deck PR's are welcome for this.

**Comment by Ph0enixMInd** [comment]
Same here.  SteamOS.  Cant enter numerals into 2fa box for MS account login.

**Comment by cgarst** [comment]
Confirmed fixed
