### ISSUE TITLE
No consoles found

### ISSUE THREAD

**Issue by Wigny** [unknownskl/xbox-xcloud-client#238]
When I open the xCloud Streaming I see "No consoles found", but in my account there is a Xbox One S linked. There are something that I am missing?

![image](https://user-images.githubusercontent.com/23202981/167263990-5eda9d41-36e3-468b-aa4f-9a76ba9fea04.png)
![image](https://user-images.githubusercontent.com/23202981/167264004-377340df-d428-4628-9d9e-bfeb304800cc.png)

**Comment by unknownskl** [comment]
Are they visible in the xbox app? You might have to enable remote configuration in your xbox settings.

**Comment by Wigny** [comment]
All I had to do for it work was "Enable remote features". Thanks for replying so fast and making this amazing project!

![image](https://user-images.githubusercontent.com/23202981/167312530-135c9c4e-b44a-4886-b848-1a3eeb0356a8.png)
