### ISSUE TITLE
[SteamOS] Unable to exit full screen mode

### ISSUE THREAD

**Issue by thirty7four2** [unknownskl/xbox-xcloud-client#280]
I can't figure out a way to send F11 to exit full screen mode when running this from Desktop mode. Is there a way to add a button to exit?

**Comment by thirty7four2** [comment]
For temporary fix for other steam deck users - I added a button to exit.

https://github.com/thirty7four2/xbox-xcloud-client/releases/tag/v1.2.0-beta4-steamdeck

**Comment by unknownskl** [comment]
You can now exit the application by tapping the xbox logo on the top left.
