### ISSUE TITLE
A Quick Start guide for Steam Deck?

### ISSUE THREAD

**Issue by Onkeyuk** [unknownskl/xbox-xcloud-client#296]
I would love to stream from my xbox to my steam deck but am new to any of this. 
please can you create a quick start guide?

I was able to run the app image from desktop mode and run full screen but no idea how to exit it. 
ive added to steam but it doesn’t open from steam in desktop or game mode 

please can we have a guide to get running with controls in game mode with the ability to close it 
Thank you

**Comment by thirty7four2** [comment]
To launch from Steam, add "--no-sandbox" as a launch option to the appimage.

Use https://github.com/thirty7four2/xbox-xcloud-client/releases/tag/v1.2.0-beta4-steamdeck which adds an exit button.

**Comment by Onkeyuk** [comment]
Thank you. I will try that

**Comment by Onkeyuk** [comment]
I’ve tried this and it works lovely in Steam now from the steam deck game mode. This should be documented in the home page as it’s essential for uses on steam deck. 

I just want to say that with my limited testing time, it’s amazing and I love you guys for building this, it’s a dream come true! So much better than my phone and controller clip 

I did have to map a rear button to f11 though as  it opens in a window by default. Would be lovely to have a open in full screen as an option
