### ISSUE TITLE
Sound is not balanced

### ISSUE THREAD

**Issue by unknownskl** [unknownskl/xbox-xcloud-client#30]
The sound output is not balanced on the left and right channels. This could be because we are not processing the audio properly.

**Comment by Finetundra** [comment]
Right channel audio may actually be absent, rather than an imbalance. Tested on Fedora with PipeWire and macOS

**Comment by unknownskl** [comment]
Fixed in beta version 1.1.0-beta1: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.1.0-beta1

**Comment by unknownskl** [comment]
Closing issue as 1.1.0 has been released
