### ISSUE TITLE
No "Cloud Library" button

### ISSUE THREAD

**Issue by connortaumoepeau** [unknownskl/xbox-xcloud-client#300]
Hi,

I have no Cloud Library button like the below image, is it because of the server I'm connected too? 

Using a MacBook Pro 16inch 2019
<img width="1621" alt="Screen Shot 2022-07-05 at 5 22 31 PM" src="https://user-images.githubusercontent.com/49574211/177255316-0afb3d01-8dd6-4bce-b6e5-ad6afde13bdc.png">

**Comment by connortaumoepeau** [comment]
Unfortunately still having issues. Definitely have a valid xCloud subscription, browser works fine or Xbox App on PC. 

I don’t have an Xbox if that’s any consolation. Can I force fetching the stream token?

**Comment by unknownskl** [comment]
Assuming you are running macOS, can you start the application via `open /Applications/Xbox-xCloud.app/Contents/MacOS/Xbox-xCloud` and check the output for any errors? The logs can contain sensitive information so make sure to remove it before sharing.

**Comment by connortaumoepeau** [comment]
Hi I did get an error while retrieving cloud token as per log below. Have removed any sensitive information. 



Last login: Sat Jul 16 17:01:06 on REMOVED
/Applications/Xbox-xCloud.app/Contents/MacOS/Xbox-xCloud ; exit;
REMOVED-MBP ~ % /Applications/Xbox-xCloud.app/Contents/MacOS/Xbox-xCloud ; exit;
Updater.ts - Checking for updates...
tokenStore: e {
  _web: { uhs: '', userToken: '' },
  _streamingToken: '',
  _xCloudStreamingToken: '',
  _xCloudRegionHost: '',
  _xCloudRegions: [],
  _msalToken: '',
  _eventOnWebToken: [ [Function (anonymous)] ],
  _eventOnStreamingToken: [ [Function (anonymous)] ],
  _eventOnxCloudStreamingToken: [ [Function (anonymous)] ],
  _eventOnMSALToken: [ [Function (anonymous)] ],
  _eventOnMSALData: [ [Function (anonymous)] ]
}
Updater.ts - Got response. Current version: 1.2.0-beta5
Updater.ts - We got the latest version already.
web tokens set
Requesting xHome and xCloud tokens..
- Error while retrieving xCloud token
  statuscode: 403
  body: {"code":"InvalidCountry","statusCode":403,"message":""}
xhome tokens set

**Comment by unknownskl** [comment]
Hi! I assume the latest update fixed the issue. Please re-open the issue if you still experience problems. Thanks!
