### ISSUE TITLE
I get about 10 frames before the app locks up and becomes useless.

### ISSUE THREAD

**Issue by Star-X555** [unknownskl/xbox-xcloud-client#306]
OS: Arch Linux
Xbox: Series S

This happened with both Appimage and npm-compiled packages, so it's not just one of the two.  For whatever reason, when I connect to my Xbox, I get about 10 frames total before it just stops sending any more to my PC.  Sound also seems to not be sent.

xCloud doesn't work on the latest AppImage, but it did work on the npm-compiled binary. Honestly though I really wanted to just stream directly from my own personal Xbox for in-home convenience.

**Comment by unknownskl** [comment]
This might be due to some decoding errors in the workers. The errors are only visible in a developer build which you can make from the source.

There is a big update planned for the video and audio which should make everything much smoother. It might be worth to wait for that update

**Comment by unknownskl** [comment]
Can you try 2.0.0-beta1 and see if that fixed all the problems with the video?
