### ISSUE TITLE
[Steam Deck] Possible to Launch in Fullscreen?

### ISSUE THREAD

**Issue by mtslzr** [unknownskl/xbox-xcloud-client#312]
Apologies if this has been answered; I was unable to find it. Is there a launch option or similar to have Steam launch the game in fullscreen (e.g. hide the menu bar)? You can do it via the View menu, but it's annoying to have to do that every launch.

**Comment by unknownskl** [comment]
Not yet, but it might be a good addition, together with a switch to auto-connect to a console

**Comment by mtslzr** [comment]
Just tried the new beta and it works perfectly!
