### ISSUE TITLE
MacOS Fullscreen mode issue

### ISSUE THREAD

**Issue by Cosmic76e** [unknownskl/xbox-xcloud-client#313]
on v1.2.0-beta6 doesn't get the fullscreen mode on MacOS

**Comment by unknownskl** [comment]
It works fine over here using the command `open /Applications/Xbox-xCloud.app --args --fullscreen`. Can you try that?

**Comment by Cosmic76e** [comment]
Tested, with the forcing command by terminal and working like a charm, thanks! Also if i resize and return back to full screen working perfectly.
Anyway when I run the App from Launchbar no able to get fullscreen mode (the green button to enlage have inside a '+' symbol used for set the windows on the desktop sides and not the usual '<' for enlarge to complete full screen.
On the previous version all is working fine for full screen with App started from Launchbar.

**Comment by MisterAnderson91** [comment]
The mouse cursor doesn't seem to auto-hide in fullscreen mode which would be great.

Otherwise, thank you so much for giving us a way to console stream on macOS.

**Comment by MisterAnderson91** [comment]
@Cosmic76e Fullscreen mode seems to be working properly on macOS in v2.0.0-beta1, you should try that version from the releases page and you can close this issue if it works for you.

**Comment by Cosmic76e** [comment]
> @Cosmic76e Fullscreen mode seems to be working properly on macOS in v2.0.0-beta1, you should try that version from the releases page and you can close this issue if it works for you.

Thanks,
I can confirm, now the issue with the fullscreen is solved on MacOS. 
I'm able to launch Greenlight in full screen without force the fullscreen mode parameter on terminal.

**Comment by unknownskl** [comment]
Great! I will close the issue.
