### ISSUE TITLE
Advertise macOS compatibility

### ISSUE THREAD

**Issue by MisterAnderson91** [unknownskl/xbox-xcloud-client#338]
Hi, I just wanted to say thank you for developing what I believe to be only native macOS app that allows Xbox Remote Play. This has been a sorely missed feature on Macs since OneCast was unable to work with Series consoles, and Microsoft blocked the Xbox ipad app from working on M1 macs after about a month.

I suggest you should update your README.md to include the platforms you are supporting and compiling for right now, which may help pick up some more attention and support for this project. 

I have taken the liberty of sharing your app on reddit [here](https://www.reddit.com/r/XboxSeriesX/comments/wfzrnt/you_can_now_remote_play_on_macs_with_new/).

**Comment by ICULikeMac** [comment]
@MisterAnderson91 Thanks for sharing on reddit. Found this amazing work from that post. 

I also want to add my thanks for developing this tool.

**Comment by unknownskl** [comment]
Hey, thank you both for the kind words, really appreciate it.
I will revise the readme soon. There are a lot of new features planned, also from the feedback. Stay tuned :-)
