### ISSUE TITLE
[Request] Nintendo Switch port (Homebrew)

### ISSUE THREAD

**Issue by Keriam** [unknownskl/xbox-xcloud-client#358]
Hello,

I don't know if this is possible but any chance to have a portage of this xcloud client to nintendo switch as homebrew ? I hope so...i have a switch OLED and android cannot be yet installed on it : Chiaki & Moonlight have switch versions, i'm dreaming  about a xcloud & geforcenow homebrew.

Thanks.

**Comment by unknownskl** [comment]
With the current codebase i dont think it is possible to port it to the Nintendo Switch. Would love to try to develop an alternative client however i do not have a device to develop on.

**Comment by openmetrue** [comment]
Hey! Now you can install ubuntu on switch oled and use linux version.
https://gbatemp.net/threads/l4t-ubuntu-a-fully-featured-linux-on-your-switch.537301/
