### ISSUE TITLE
Clarity Boost option

### ISSUE THREAD

**Issue by amon-666** [unknownskl/xbox-xcloud-client#359]
https://news.xbox.com/en-us/2021/11/29/clarity-boost-with-xbox-cloud-gaming-on-edge-browser/

Hello, I am currently able to toggle the Clarity Boost option in the Xbox cloud with a Microsoft edge browser. Can I also use this feature in the Xbox-xcloud-client?

**Comment by unknownskl** [comment]
Currently the edge browser uses some custom api's to sharpen the video. Electron / Chrome does not support that unfortunately.
