### ISSUE TITLE
MacOS's green fullscreen button breaks app

### ISSUE THREAD

**Issue by cgarst** [unknownskl/xbox-xcloud-client#360]
The standard macOS green button to full-screen a window causes the app to shrink into the lower left hand corner to never been seen again. To get it back you need to close and re-open. This is the case either in the xbox-xcloud-client menu or with an active stream.

Version: 1.2.0
Hardware: MacBook Air M1

**Comment by MisterAnderson91** [comment]
This seems to be fixed in 2.0.0-beta1, try updating to that version from the releases page and see if you still get the same behaviour. The app will have the new name "Greenlight.app" in your applications folder.

**Comment by cgarst** [comment]
Yes it is fixed now, thank you. 2.0 beta looks great.
