### ISSUE TITLE
WebUI stream working but client didn't

### ISSUE THREAD

**Issue by TkzcM** [unknownskl/xbox-xcloud-client#401]
Hello, I'm using v1.2.0 on macOS M1 Pro, the WebUI stream is working everytime, but the client stream will show black screen after a few seconds played, no sound either. Sometimes client works, but I have to retry many times to get it work.

**Comment by MisterAnderson91** [comment]
There's a new 2.0.0-beta1 release, try grabbing that one and see if it works.

**Comment by TkzcM** [comment]
It works pretty well now, thanks for your hard work. Although there's another problem, if xcloud isn't available in the region of user, the login button is not working.

**Comment by MisterAnderson91** [comment]
I would open a separate issue for that.

**Comment by unknownskl** [comment]
Good to hear the new version fixed the issue. For the non functioning login button please create a new issue with some screenshots / steps to reproduce it. i will continue and close this issue for now.
