### ISSUE TITLE
macOS doesn't launch with correct sign-in window

### ISSUE THREAD

**Issue by MisterAnderson91** [unknownskl/xbox-xcloud-client#411]
Not sure if this is intended behaviour, but 2.0.0-beta1 is launching with what seems to be intended to be the sign-in window, at the homepage of xbox cloud gaming (beta) instead.

Going to the "profile" icon and clicking sign-in, then following the sign-in process, seems to give the intended behaviour (the window closes when sign-in completes and the main window for the app refreshes signed-in).

Screenshot attached of the two windows opened on a fresh install.

![image](https://user-images.githubusercontent.com/50129983/191764497-6961da75-2111-49d2-8cdd-022673092556.png)

**Comment by MisterAnderson91** [comment]
Restarting the app after signing in seems to work fine; the secondary window shows a blank white page momentarily and disappears and the main window loads.

**Comment by unknownskl** [comment]
Fixed in 2.0.0-beta1
