### ISSUE TITLE
ERROR IN PROMISE 

### ISSUE THREAD

**Issue by Paulc19-93** [unknownskl/xbox-xcloud-client#422]
Getting this message when trying to remote play, can't seem to get past it.

Error in promise: {"state":"Failed","detailedsessionstate":0,"errordetails":{"code":"ProvisiongTimedOut","message":"Agent : ServerNeverRegistered : Server never registered with service : StateWaitingForServerToRegistser"}}

**Comment by unknownskl** [comment]
Can you try to fully power cycle the Xbox and try again?

**Comment by Paulc19-93** [comment]
Power cycled and that fixed the issue. Issue then came back when trying to boot from xbox in standby mode. An hour later as long as the device is power cycled and om you can connect but can't get it to in standby mode

**Comment by Zamrod** [comment]
I get the same error when attempting to look at the list of cloud games.

**Comment by levelfungames** [comment]
> 

Same for me... "Error in Promise: {}" whenever I attempt to load xcloud game library

**Comment by ejleslie** [comment]
Also experiencing this error when I try to load the XCloud game library.

**Comment by unknownskl** [comment]
As the error comes from the xcloud api's we cannot do much about this error unfortunately
