### ISSUE TITLE
Cant stream original xbox games

### ISSUE THREAD

**Issue by blissband123** [unknownskl/xbox-xcloud-client#47]
When i load a og xbox and 360 game i get the error code 0x87e10004
![16318421709248041514728016604983](https://user-images.githubusercontent.com/63673583/133709280-a72f75e1-7eba-4093-9c47-0906109f77bd.jpg)

**Comment by unknownskl** [comment]
This message is coming from the Xbox itself. Microsoft may have limited streaming of some xbox og / xbox 360 games.
