### ISSUE TITLE
Press and hold with keyboard mappings causes button repeat

### ISSUE THREAD

**Issue by padic-dev** [unknownskl/xbox-xcloud-client#489]
MLB the Show 2022 is a game where I noticed this case. During cut scenes you can press and hold the A button on the controller to skip the scene. When I attempt this using the keyboard mapping to the A key, it performs a repeat keypress which makes it impossible to skip these scenes. While I recognize this could actually be counter productive for games where keypress repeat will be beneficial I am not sure if this can be addressed in anyway that would be beneficial to the overall usage of this wonderful app. If there is anything that can be done to provide a press and hold feature that would be great. If not completely understood and of course this would be extremely low priority as I don't see this being mentioned by anyone else.

**Comment by unknownskl** [comment]
v2.0.0-beta2 has been released with an improvement for keyboard control. Please try that version.
