### ISSUE TITLE
Unable to sign in on Mac - Error code: la3/sGb4/2WBt7ZiVy+EEv.14

### ISSUE THREAD

**Issue by angelgenkov** [unknownskl/xbox-xcloud-client#490]
I am unable to sign in when using the latest build on Mac OS.
I can click the sign in once, enter my email and password, then I get this screen and I can no longer click on Sign in, its just plain text.
![Screenshot 2022-10-23 at 13 28 44](https://user-images.githubusercontent.com/12477621/197387232-196824b1-873f-4330-835a-98aca423b246.png)

**Comment by unknownskl** [comment]
This was an iCloud issue. See #508
