### ISSUE TITLE
Clear Microsoft Login Cache

### ISSUE THREAD

**Issue by Distant2k** [unknownskl/xbox-xcloud-client#499]
Hi there.

I recently logged out of the client but when logging in, I selected to "Dont Remember details" and ticked the "Don't show this again" tick box.

Could you advise where you are caching this so I can delete it? 

Thanks

**Comment by Distant2k** [comment]
Resolved issue with full Steam Deck Factory Reset. Would be nice though to know where you store this information

**Comment by ghagiel** [comment]
> Resolved issue with full Steam Deck Factory Reset. Would be nice though to know where you store this information

Home / .config / xbox xcloud

**Comment by unknownskl** [comment]
You should also be able to logout via the settings page. That should remove all local cache files and tokens.
