### ISSUE TITLE
Can't seem to finalize login

### ISSUE THREAD

**Issue by Dwosky** [unknownskl/xbox-xcloud-client#508]
Not sure if Microsoft changed anything, but it seems the OAuth or whatever method the app is using to validate with Microsoft its not working correctly, since you end in a page like this:
![image](https://user-images.githubusercontent.com/72130275/198065724-c6458ed1-328a-4f83-ac0d-e94c96592115.png)

If I clear the contents of Xbox-xCloud configuration folder, it will ask for my login credentials and successfully login within Microsoft, but upon returning it will end in the same 404 error page.

Not sure if its the same as the other Mac issue https://github.com/unknownskl/xbox-xcloud-client/issues/490, since that one has an error message and I don't get any.

I've also tested the 2.0.0 beta version and I end in the same error as well:
![image](https://user-images.githubusercontent.com/72130275/198068386-d53fc7bb-a78e-41e3-b7b4-04769b8005e8.png)

**Comment by baltimoresports** [comment]
Confirmed same issue.
Version: 1.2.0 & 2.0 Beta
macOS: 12.5.1
M1 Mac

**Comment by Distant2k** [comment]
This was due to Xbox Live being down. This should be working again now

**Comment by Dwosky** [comment]
As @Distant2k pointed out, it was due to Xbox Live being down and now works as expected. Closing the issue as its working again.
