### ISSUE TITLE
Some degree of input lag on steam deck 

### ISSUE THREAD

**Issue by gsabater** [unknownskl/xbox-xcloud-client#681]
Hello, i would like to know the experience of other users and tips on this topic.

My setup is Xbox series X wired to the router, and a wifi6 router literally next to the steam deck.

The image quality is superb, crisp and without any stuttering. According to the steam deck stats and my experience is rock solid 60 fps.

But I sense some degree of input lag. I tried measuring it using the calibration tool on metal Hellsinger and it ranges about 100-200ms.

Using moonlight with PC the sensation of delay is much lower, so i discard network problems.

Any thoughts ?

**Comment by XanderQue** [comment]
I noticed lag last night when remote playing, I played on the android and it was good. I wonder if something changed in the backend on xbox side or something. Tried to come here to see if I was the only one.
