### ISSUE TITLE
Connection Error SD

### ISSUE THREAD

**Issue by Crypsie** [unknownskl/xbox-xcloud-client#705]
I'm receiving the following error when trying to connect:

Error S Promise: {"state"."Failed" "detailedSessionState":
"errorDetails":{"code":"xccsClientHttpError" "message":"Xccs: XccsError XccsClient: Response status code does not meet expectations. StatusCode: InternalServerError Expected: OK
BadRequest Unauthorized NotFound State
WaitingForServerToRegister "}}

It worked fine a few times before this. I can't find any information by searching. Thanks

**Comment by Abisco** [comment]
I’m getting exact same issue, it’s been fine up till today.

**Comment by Crypsie** [comment]
Yep, same up until today no issues. I've tried everything I could possibly think of/find, all to no avail. Hopefully it's something that's easily fixable

**Comment by demaggus83** [comment]
I can confirm the problem.

Mac (M1) => Xbox Series X
Steam Deck => Xbox Series X

Girlfriend:
Steam Deck => Xbox Series S

**Comment by lommes** [comment]
https://www.xbox.com/status reports problems with remote and cloud play, so this might be related

**Comment by gsabater** [comment]
> https://www.xbox.com/status reports problems with remote and cloud play, so this might be related

Just a question, isn't supposed to use remote play the local network to stream in home? I guess that it uses MS servers to route ports and such, but why is this necessary?

**Comment by demaggus83** [comment]
Everything is working again. So this ticket could be close!

@gsabater If I would need to place a guess, I would assume it's because you could also stream over the internet

**Comment by Crypsie** [comment]
Yep, came home and all back in order again. Hurray! Must've been on MS' side. Ticket closed
