### ISSUE TITLE
Can't load any game Error in Promise; Details Failed to sign in with transfer token, perhaps due to invalid transfer token from the client

### ISSUE THREAD

**Issue by VladiJu** [unknownskl/xbox-xcloud-client#717]
First of all, I want to say thank you, I see that this is mostly a one man work, and thanks to you (unknownskl) I have been able to happily play on a 2011 Macbook, this thing cannot run a YouTube video on 720p, It was totally impossible to play on a browser, but with your work I have been able to enjoy so many games and hours, I'm truly grateful for it.
I feel bad for posting my issue since I feel like I'm asking for you to fix, when you have already worked, I guess a lot, and gave it to everyone to enjoy, and yet, I'm here asking you to keep working and fixing things, sorry, If I knew how this worked, I would help, I'm trying to learn, tho :(
The issue in question is this:
I launched to program as always, but this time it asked me for my password again, so I put it on again, After I logged in, the log-in window stayed open and showed me the main page of XCloud; (note: if I clicked on my account, the window closes automatically) after that, I got an error when trying to see the game library, I updated my version from 2.0.0 Beta1 to 2.0.0 Beta2, but it has a very similar problem, the library shows the games, but when I try to open one I get this error;
> Error in Promise: {"state":"Failed","errorDetails":{"code":"Unknown","message":"Type:  UserError : InternalCode :TransferTokenPackageDecryptFailed : Details Failed to sign in with transfer token, perhaps due to invalid transfer token from the client Fault: [-2147215358 at xbox\\streaming\\managementservice\\server\\addandsigninuserv2operation.cpp:72\tclass Network::AddAndSignInUserV2Command failed.]"}}

I tried with version 1.2 and I get a very similar problem, no error code, just infinite loading

**Comment by wesmoen** [comment]
Yesterday, when I downloaded the program I ran into the same issue. this morning I fix it by, opening the program, logging out and logging in again, starting an XCloud game and exiting that game. 

I also applied the "Don't forget this device in the future" and "You can automatically sign in".

**Comment by lasagneking** [comment]
Same issue, local streaming works great although xcloud always gives the same error reported by the OP.

i tried the suggestion of logging out and back in again although the same message was displayed.

**Comment by lasagneking** [comment]
Guessing this no longer supported?

**Comment by VladiJu** [comment]
> 

I tried that, but I didnt't work :(

**Comment by VladiJu** [comment]
> > 
> 
> I tried that, but I didnt't work :(

**Comment by unknownskl** [comment]
Error should have been fixed with 2.0.0-beta3.

**Comment by RJNY** [comment]
Hello, I’ve upgraded from v1.X to 2 beta 3 and I started getting these errors when attempting to home stream or xCloud. 

Fwiw; it worked the first night perfectly, but have been getting this error since. 

Let me know if I should provide further information. 

Thanks for all your hard work with this btw!
