### ISSUE TITLE
Error: node-loader, the specified module could not found

### ISSUE THREAD

**Issue by kohanyirobert** [unknownskl/xbox-xcloud-client#775]
Building the latest version on main-v2 with xal-node I get the following on Windows 10 when running the .exe in the dist/win-unpacked folder (same happens when using the installer).

![image](https://user-images.githubusercontent.com/1104829/226175259-e219945d-c2da-4a16-8f3d-10b2eb7814c8.png)

Any idea? 🤔

**Comment by unknownskl** [comment]
It looks like the xal-node library didn't build successfully. Can you try to run `yarn run build-deps` and see if that will solve the issue?

Update: Also try to update the modules by running `yarn`

**Comment by kohanyirobert** [comment]
My bad. It seems I've provided the shared OpenSSL libs I've built with `vcpkg` by setting `OPENSSL_DIR` for the `cargo` build.
Just for future reference for myself and others who make this mistake:
1. Install `openssl:x64-windows-static` with `vcpkg`
2. Set `OPENSSL_DIR` to `<vcpkg_root>\installed\x64-windows-static`
3. Set `OPENSSL_NO_VENDOR` to `1`
4. Set `RUSTFLAGS=-Ctarget-feature=+crt-static` ([as described here](https://docs.rs/vcpkg/latest/vcpkg/#windows))
5. Do the build :)
