### ISSUE TITLE
You'll need a new app to open this ms-xal-public-beta

### ISSUE THREAD

**Issue by kohanyirobert** [unknownskl/xbox-xcloud-client#776]
![image](https://user-images.githubusercontent.com/1104829/226188324-4e2985ef-1e1e-49e9-818c-2fbacbbaf45e.png)

After successfully building and starting the app I get the following when logging in.

**Comment by unknownskl** [comment]
Can you check if you have the latest changes? There was a hotfix committed yesterday.
In case it still happens then let me know and i will try to reproduce it on my side.

**Comment by kohanyirobert** [comment]
Yes, it seems to work with the hotfix. Sorry about that, after successfully building the stuff (xal-node) I forgot to do a pull. My bad again. Thanks!
