### ISSUE TITLE
Popup with confirmation to sign in to Game Pass every time app is opened

### ISSUE THREAD

**Issue by rakleed** [unknownskl/xbox-xcloud-client#782]
After switching to a new authentication system, each time you open the application, the following popup appears:
![Screenshot 2023-03-21 at 20 01 57](https://user-images.githubusercontent.com/19418601/226687114-cbfdd9cf-ca80-45ce-944b-1eba7d7f28c1.png)

Although earlier it was necessary to enter a login, password and optionally 2FA when opening the application for the first time, but then the pop-ups with login confirmation never appeared again.

**Comment by dsoms** [comment]
Same issue here with my XBOX Series X on my Steam Deck.

**Comment by joshthor3222** [comment]
I have the same issue. One additional thing to note - most of the time when i sign into my xbox account it prompts me to remember, but the login prompt seems to glitch out at that step and hangs after submitting password forever. if i close and reopen, i am logged in, but it never makes it to that prompt which i think is causing the issue

**Comment by unknownskl** [comment]
v2.0.0-beta7 just released and should save the tokens and only prompt when the token needs to be refreshed. Please try it out :)

**Comment by ashmckenzie** [comment]
Thanks @unknownskl, tested and after an initial popup confirmation it didn't ask again, awesome! 👍
