### ISSUE TITLE
Login and Stream issues

### ISSUE THREAD

**Issue by moro-7** [unknownskl/xbox-xcloud-client#788]
At launch, it asks me to confirm login, continue goes back to the same confirmation page. then I get:
Uncaught Exception:
TypeError: Object has been destroyed
at Function.<anonymous> (/Applications/Greenlight.app/Contents/Resources/app.asar/app/background.js:1:78644)
If i just close the login window it seems to work just fine, with me logged in (it shows the console and online friends too)

but when I try to stream, I get:
Error in Promise: {"state":"Failed","detailedSessionState":0,"errorDetails":{"code":"ConsoleStreamingDisabled","message":"Xccs : ConsoleStreamingDisabled : User has disabled streaming on Xbox: FD00096D1F3F40F8 : State WaitingForServerToRegister"}}

I get this error in v4, v5, and v6, which are all the versions I've tried.

**Comment by lasagneking** [comment]
Did you find a fix?  Am getting the same issue!

**Comment by carterlasalle** [comment]
@lasagneking @moro-7 It says, "ConsoleStreamingDisabled : User has disabled streaming on Xbox: FD00096D1F3F40F8 " 

Make sure to enable remote play on your xbox in the settings!
