### ISSUE TITLE
Reference of #776

### ISSUE THREAD

**Issue by HerXayah** [unknownskl/xbox-xcloud-client#790]
So im referncing Issue #776 
Latest beta and im getting this again
![image](https://user-images.githubusercontent.com/45071533/227963964-efd6a598-6c66-4aa7-b981-d03a264707f4.png)

**Comment by HerXayah** [comment]
Edit:

To get in regardless wait until it loads then close.
It will ask you if you wanted to login and will continue regardless

**Comment by unknownskl** [comment]
The issue should be solved in v2.0.0-beta6. Can you check if the problem is fixed for you?

**Comment by MPThLee** [comment]
I'm getting this issue again since today. can you check it? @unknownskl

Of course, I'm using beta6.

**Comment by unknownskl** [comment]
I've been able to reproduce the issue on my side. Will check it and provide an update later.

**Comment by unknownskl** [comment]
v2.0.0-beta7 has been released and should (hopefully permanently) fix the issue. Please let me know if it works as expected

**Comment by unknownskl** [comment]
Issue closed due inactivity
