### ISSUE TITLE
Bitrate selection

### ISSUE THREAD

**Issue by generalmidi445** [unknownskl/xbox-xcloud-client#804]
Thanks for your work! Bitrate selection is the killer feature of your client compared to the original xbox-app. However, it doesn't work for me (Beta 6 on Windows 11). No matter what I select it is always locked to the default 15Mbit/s. Am I doing something wrong?
Regards

**Comment by mindesik** [comment]
Same here, selected 100 Mbit/s but it looks like 10-20 (home xbox console)

**Comment by eahlys** [comment]
Same issue, using remote play (not xCloud streaming)

**Comment by unknownskl** [comment]
The Xbox locks it to max 15 mbps. Only microsoft can increase this limit.
