### ISSUE TITLE
Clicking Login appears to not function for me;

### ISSUE THREAD

**Issue by HybridZach** [unknownskl/xbox-xcloud-client#815]
Not sure if I am missing something here, but I can not seem to get past the first screen "Login with xbox", clicking Login appears to not function for me. I am on Windows 11, I have tried to click clear data, run as admin, run as windows 8 no dice, tried the installer, and portable version, also side note when closing the app, it stays open in the background for some reason too. 

Same issue for beta 6 & 7.

**Comment by Dwosky** [comment]
Not sure if its the same issue, but upon launching v1.2.0, I get the login popup with the following error:
![image](https://user-images.githubusercontent.com/72130275/233793762-99adcd93-519e-4da3-b7f2-560f14114a48.png)

From the logs, this seems to be the related error:
```
Updater.ts - Got statuscode: 301 {"message":"Moved Permanently","url":"https://api.github.com/repositories/386752959/releases","documentation_url":"https://docs.github.com/v3/#http-redirects"}
```

Version 2.0.0-beta7 seems to be able to login successfully and I can see the main screen with the Xbox Console's info. Not sure if something changed from Microsoft and wasn't updated on the previous version.

**Comment by Hukolla** [comment]
I am too. Cant Login here. Maybe need Xbox app?
![image](https://user-images.githubusercontent.com/131584428/233830106-7b6d7960-76fd-478d-a92a-27360d573d1e.png)
Work only Clear dara, button Login not work for me

**Comment by arongkatz** [comment]
Im on the same boat but on steam deck desktop mode

**Comment by unknownskl** [comment]
The newest update should fix this issue with the non working login button. Please let me know if you are still experiencing issues.

**Comment by stevelatta** [comment]
I'm still having this issue on Steamdeck, specifically running the windows version in Proton.  I can't get the linux version to run in game mode either.  Linux version does work in desktop mode though, and login works in that version in desktop window mode.

**Comment by shotalot09** [comment]
I'm getting the same problem, but in Windows. Using beta10 on Windows 11, can use the Clear Data button but the Login button doesn't seem to do anything.

![image](https://github.com/unknownskl/greenlight/assets/28712898/68d3ccb7-9275-4e70-b0a3-e835e20b3398)

**Comment by Buscapedehuynh** [comment]
As of Oct 4 using newest version I have this same issue...

**Comment by unknownskl** [comment]
I don't think this issue is happening anymore. Please reopen the issue if the buttons are still broken.

**Comment by RitschiRitsch** [comment]
This issue is still persistent on Windows 11 with 2.0.1 and the beta ones (beta 7, 14 and 15 tested). On Windows 10 it works just fine.

Update: The issue was the time setting. On my Windows 11 machine the time setting was not correct / synced (was 1 hour behind) that prevented the login window to pop up.
