### ISSUE TITLE
[steam deck] Out of home network NEVER gets remote play working

### ISSUE THREAD

**Issue by arnimi** [unknownskl/xbox-xcloud-client#829]
Hi,

On v2.0.0-beta7 if i'm on home network with xbox and steam deck on it I can see the xbox on the list and remote play, but if I'm out of home and trying to connect from other network I can see the xbox listed but if I try to connect to remote play this connection is never done.

It stops on "Connecting to console...".

I have tested that I can connect from out of home network to xbox with iOS app.
Also I have tested to power on the xbox from iOS app and then try to remote play from green light steam deck app, but it doesn't gets to connect.

Many thanks!

**Comment by bchilton9** [comment]
I have the same problem.

**Comment by unknownskl** [comment]
Hey there,

Please check the pinned issue #593

I understand this is a much requested feature but it is quite difficult to get remote streaming implemented. It requires use of Teredo which is very difficult to implement cross-platform. As an alternative you could try to use a VPN or Wireguard to  connect to your home network.

**Comment by arnimi** [comment]
Why didn't I think of VPN?

Lucky me I have VPN at home. I tested it and it's working perfect.

Many thanks!

**Comment by colindavidr** [comment]
Has any progress been made since this comment to implement a feature to make this work?
