### ISSUE TITLE
Webui plugin on latest release

### ISSUE THREAD

**Issue by blitz2kx** [unknownskl/xbox-xcloud-client#862]
Great app, thank you for the hard work on this. I know plugins are not available on the latest betas, however the webui unlocks tremendous potential with GPU upscaling for browser video content now available.

Testing the old stable release of the webui with Nvidia Super Resolution tech yielding pretty amazing results. This feature making its way back to the app with the new features such as haptic feedback would be awesome.

Anyway thanks for the work on this 🙏 Cheers.

**Comment by unknownskl** [comment]
Progress on the Web UI has been started and is expected to be released somewhere later this month.

Also i will close this issue as we already have #673.
