### ISSUE TITLE
There is no sound on Steam Deck when using Greenlight.

### ISSUE THREAD

**Issue by liamhhhzzz** [unknownskl/xbox-xcloud-client#863]
why does my deck have no sound when streaming, the xbox audio settings display "Headphones are connected", but i am not using headphones.

**Comment by HokiMinato** [comment]
I have the same issue. Did it work for you, do you found any solution ?

**Comment by paulkrupin** [comment]
I have the same issue at the time of writing. Rebooting Xbox or Greenlight on Steam Deck doesn't help.

**Comment by paulkrupin** [comment]
Also, I've tried to re-login but it didn't help either.

**Comment by goranpaues** [comment]
Unmuting Chromium fixed the issue for me. See https://www.reddit.com/r/SteamDeck/s/rSHmDUg5ID

**Comment by paulkrupin** [comment]
@goranpaues Thank you, will try it.
