### ISSUE TITLE
Key maps works on game menu but not inside the game

### ISSUE THREAD

**Issue by kadiryunusdemir** [unknownskl/xbox-xcloud-client#878]
I have an M1 with a Turkish layout. I tried NFS Unbound, and the keymaps work well for the game's menu. However, when I attempted to drive the car using the arrow keys, the LB and RB keys didn't work. Both the '?' and '-' keys functioned as LT."

**Comment by unknownskl** [comment]
It has been a while ago but the keyboard mappings should be fixed now. Can you verify if the problem has been solved on your end too?

**Comment by kadiryunusdemir** [comment]
Thanks, it's fixed. When I look at it now, I see that keyboard mappings have been added. Great feature. I wish there was a way to use thumbsticks as well.
