### ISSUE TITLE
Greenlight Wont log in to Remote Play/xCloud MacOS

### ISSUE THREAD

**Issue by ExcelsiorGamingYT** [unknownskl/xbox-xcloud-client#894]
My greenlight has been working fine until today, now it just wont log in at all. I keep getting send back to the log in screen everytime and it just does nothing. Its nothing to do with xbox as i can still log in to remote play via my phone but the mac app isnt working at all. I have restarted both my mac and xbox, aswell as also reinstalling greenlight to no avail.
Please help......

![Screen Shot 2023-07-26 at 08 26 09](https://github.com/unknownskl/greenlight/assets/140591650/1aa0390d-019f-43f9-8dcd-c4c8023acddb)

**Comment by unknownskl** [comment]
On which version does this happen? If you are not on the latest version yet, please try to update the application.
The newer versions have a 'Clear data' button on the login view which can sometimes resolve issues with the authentication

**Comment by jshessen** [comment]
I am currently on Linux, and I am getting the same type of response on Beta 9 (after clearing my data):

`$ ./Greenlight-2.0.0-beta9.AppImage --trace-warnings
/tmp/.mount_GreenlWGwIbE/resources/app.asar/app/background.js[constructor()] Starting Greenlight v2.0.0-beta9
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to fetch session id"', src/rs_xal_authenticator.rs:197:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(node:280465) UnhandledPromiseRejectionWarning: Error: sending on a closed channel
    at XalAuthenticator.close (/tmp/.mount_GreenlWGwIbE/resources/app.asar/app/background.js:1:682)
    at /tmp/.mount_GreenlWGwIbE/resources/app.asar/app/background.js:1:97783
(Use `greenlight --trace-warnings ...` to show where the warning was created)
(node:280465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:280465) UnhandledPromiseRejectionWarning: Error: sending on a closed channel
    at XalAuthenticator.close (/tmp/.mount_GreenlWGwIbE/resources/app.asar/app/background.js:1:682)
    at /tmp/.mount_GreenlWGwIbE/resources/app.asar/app/background.js:1:97783
(node:280465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
`

**Comment by ExcelsiorGamingYT** [comment]
It's seems to be just being temperamental one minute it'll work then it won't then it will again...

**Comment by jshessen** [comment]
@ExcelsiorGamingYT  -- I will shift my comments to a new issue then as mine is 100% failure rate (Linux AppImage)

**Comment by thejae** [comment]
Having the same issue on beta8 and beta9. It works flawlessly at home within the same network but once outside, it doesn't connect anymore. (Although it works on iPad Xbox app)

On Mac OS Ventura 13.4.1

=== EDIT ===
It no longer works at home within the same network either. So yeah, completely stuck at Getting your stream ready screen.

=== EDT 2 ===
Beta 7 still works!

**Comment by ExcelsiorGamingYT** [comment]
Yeah my problems are back today worse than ever, now the login screen comes up with sorry this cant be found or have moved. Im on Beta 3 as any other betas i try just come up with javscript errors and dont open. im on High Sierra if that helps
