### ISSUE TITLE
issue starting up Beta 10 on Mac OS

### ISSUE THREAD

**Issue by seancoz** [unknownskl/xbox-xcloud-client#898]
I had been running Beta 2 for months but had to change my microsoft account password and it continued giving me an error message at startup. I downloaded beta 10 and when opening the program I get "A JavaScript error occurred in the main process. Not sure what I'm doing wrong

**Comment by unknownskl** [comment]
Can you please post the full error message? It contains the error which is helpful to know what is going wrong.

**Comment by seancoz** [comment]
I re-opened it up and this time it said 'Startup error' with the following:

 XAL Authentication library failed to load. Error: Error: node-loader:
Error: dlopen(/var/folders/dm/jvffgp_55dj4pb0nrfd0kl3w0000gn/T/.com.unknownskl.greenlight.ih5oxp, 1): no suitable image found.  Did find:
	/var/folders/dm/jvffgp_55dj4pb0nrfd0kl3w0000gn/T/.com.unknownskl.greenlight.ih5oxp: cannot load '.com.unknownskl.greenlight.ih5oxp' (load command 0x80000034 is unknown)
	/var/folders/dm/jvffgp_55dj4pb0nrfd0kl3w0000gn/T/.com.unknownskl.greenlight.ih5oxp: stat() failed with errno=17

**Comment by ExcelsiorGamingYT** [comment]
i get that error message on anything after beta 3, so im stuck with Beta 3 which will now never login and just sits on the login screen now and does nothing.

**Comment by seancoz** [comment]
> i get that error message on anything after beta 3, so im stuck with Beta 3 which will now never login and just sits on the login screen now and does nothing.
I just downloaded Beta 3 and it finally allowed me into the program but yeah I'm stuck at the loading screen as well, trying to see if there's anyway to sign out and sign back in because prior to changing my password I literally had no issues

**Comment by unknownskl** [comment]
Which Mac os version are you using? Tested it on Ventura and cannot replicate the error.

**Comment by ExcelsiorGamingYT** [comment]
> Which Mac os version are you using? Tested it on Ventura and cannot replicate the error.

I'm running High Sierra 10.13 and I cannot login at all been happening since Saturday. Also I cannot use any beta apart from betas 1-3 all the others have error messages I done my own issue ticket for this aswell

**Comment by anatolyzaitsev** [comment]
The same issue on Big Sur(11.3.1)
Pulled [fix from unknownskl](https://github.com/unknownskl/greenlight/commit/a0ef9c2ac8817310161d8f3d6be04b3a9b980d4b) to source code but still have this error on startup:

<img width="299" alt="image" src="https://github.com/unknownskl/greenlight/assets/125252988/ac9a0100-704c-41d7-89cd-f1c2833cfa2f">

Building log:
```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Collecting page data    
 ✓ Generating static pages (12/12) 
 ✓ Finalizing page optimization    

Route (pages)                              Size     First Load JS
┌   /_app                                  0 B            84.4 kB
├ ○ /404                                   350 B          84.8 kB
├ ○ /500                                   357 B          84.8 kB
├ ○ /achievements/[titleid]                951 B          85.4 kB
├ ○ /debug                                 470 B          84.9 kB
├ ○ /example                               457 B          84.9 kB
├ ○ /home                                  4.28 kB        88.7 kB
├ ○ /next                                  381 B          84.8 kB
├ ○ /profile                               427 B          84.9 kB
├ ○ /profile/[xuid]                        422 B          84.8 kB
├ ○ /settings                              1.57 kB          86 kB
├ ○ /stream/[serverid]                     35.7 kB         120 kB
└ ○ /xcloud/home                           1.43 kB        85.9 kB
+ First Load JS shared by all              108 kB
  ├ chunks/framework-cbdf004c5e39eb73.js   45.2 kB
  ├ chunks/main-b69ea32949eb20aa.js        31.4 kB
  ├ chunks/pages/_app-91fe7ac144f2d964.js  7.05 kB
  ├ chunks/webpack-009e99a7acfa5ee0.js     727 B
  └ css/29af55938349b00c.css               23.9 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

 ⚠ "next export" is deprecated in favor of "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
   using build directory: /Users/AZ/greenlight/renderer/.next
   Copying "static build" directory
   Launching 7 workers
   Copying "public" directory
 ✓ Exporting (13/13) 
Export successful. Files written to /Users/AZ/greenlight/app
[nextron] Building main process
[nextron] Packaging - please wait a moment
  • electron-builder  version=24.6.4 os=20.4.0
  • loaded configuration  file=/Users/AZ/greenlight/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=25.8.2 appOutDir=dist/mac-universal-x64-temp
  • packaging       platform=darwin arch=arm64 electron=25.8.2 appOutDir=dist/mac-universal-arm64-temp
  • packaging       platform=darwin arch=universal electron=25.8.2 appOutDir=dist/mac-universal
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, it could cause some undefined behaviour, e.g. macOS localized description not visible, see https://electron.build/code-signing allIdentities=  1) 4D40D3511700AC45793256C959D6030E8A8A4EB6 "hideme_69629635871388" (CSSMERR_TP_CERT_EXPIRED)
     1 identities found
                                                Valid identities only
     0 valid identities found
  • building        target=DMG arch=universal file=dist/Greenlight-2.0.0-beta14-universal.dmg
  • building block map  blockMapFile=dist/Greenlight-2.0.0-beta14-universal.dmg.blockmap
[nextron] See `dist` directory
✨  Done in 78.17s.
```

**Comment by unknownskl** [comment]
Please try the new 2.0.0-beta15. It should hopefully fix the issues :)
