### ISSUE TITLE
Feature Request: Introducing 'Free Xcloud Games' Category for Xbox Accounts without Game Pass Ultimate

### ISSUE THREAD

**Issue by coolgamerkid332** [unknownskl/xbox-xcloud-client#918]
So, here's my idea: if you've got an Xbox account without Game Pass Ultimate, you'd still see a section called something like "Free Xcloud Games." That's where all the games you can play for free would be listed. Right now, it's just Fortnite, but who knows, more might be added later on. For folks with Game Pass Ultimate, the games would stay in the "xCloud Library" tab, just like they are now. Thanks for listening!

**Comment by unknownskl** [comment]
Done, has been implemented since 2.0.0-beta13
