### ISSUE TITLE
Update "latest" version to a 2.0 build

### ISSUE THREAD

**Issue by MisterAnderson91** [unknownskl/xbox-xcloud-client#938]
Version 1.2 is still showing as the "latest" release, maybe due to beta tags on 2.0

Is 1.2 still working well enough to leave it there? It seems that 2.0 is functioning much better and should be the default link.

I propose that it's time to set the v2.0 branch to full release to avoid confusion for people downloading directly off the project's github homepage. It has excellent functionality at this point and minor version numbers can replace the beta numbers.

![image](https://github.com/unknownskl/greenlight/assets/50129983/41a6d9b3-ff26-4104-a713-9e36cba26b0c)

**Comment by gh0sti** [comment]
@MisterAnderson91 2.0 isn't fully ready to go into release candidate, especially with the bug with streaming from the console being a hit-and-miss with the community.

See https://github.com/unknownskl/greenlight/issues/896

**Comment by MisterAnderson91** [comment]
@gh0sti Regardless, I don't think recommending 1.2.0 on the main page is the right move. Does that build even work anymore? I don't remember it being any less buggy than the v2.0 betas.

**Comment by unknownskl** [comment]
Agree that we should promote 2.0 to the latest version, however there are many small things that need to be wrapped up before we can promote to a real stable release. (Hopefully this year still as my time is a little bit limited at certain times)

On the 1.2.0 release page it has a big text mentioning that 2.0.0 beta works better. I think that should be enough for the time being.
