### ISSUE TITLE
Failed to stream Xbox one slim after console firmware updated to version 10.0.25398.1762

### ISSUE THREAD

**Issue by phillipedolin012** [unknownskl/xbox-xcloud-client#942]
Hi dude,

      the latest release failed to stream, it reported error "code: WNSError, ... State: waitingforServerToRegister" and stuck there.
      It could work with my xb1 console last week. 
      I found the main change might be my console updated firmware to version  10.0.25398.1762. 
      Did it matter ?

Thanks

**Comment by unknownskl** [comment]
Try to reboot / power cycle the xbox. This happens sometimes when the console has lost connection to the xbox servers which can be fixed by restarting.
