### ISSUE TITLE
infinte loading screen on beta 12.

### ISSUE THREAD

**Issue by Anaythesteve123** [unknownskl/xbox-xcloud-client#948]
I am using a M1 Mac running Ventura 13.4.1. when I try streaming my Xbox it just says: starting your stream, connecting to your console. or sometimes it just gives me an error in Promise 401. please fix this because I really like using this, especially for using Bluetooth headphones on my Xbox.

**Comment by humza2000** [comment]
same beta 12 gives me the same issue. works perfectly on my local network but not when I am trying to connect remotely.

**Comment by moisesbelda** [comment]
For me it is failing since beta9, and if I shutdown the client 1 or 2 times, and start the connection again, it works.
Take a look : #950

**Comment by Anaythesteve123** [comment]
> same beta 12 gives me the same issue. works perfectly on my local network but not when I am trying to connect remotely.

its not even working on my own local network.

**Comment by Anaythesteve123** [comment]
i am using a series S

**Comment by moebiusmania** [comment]
same here with app beta 14, Xbox Series X and Macbook Air M2. It's almost flawless in local network but when on different network it keeps loading.

Console stream never connects, xCloud sometimes fails (even when an eventual "too many people" countdown reaches 0) sometimes works

**Comment by Anaythesteve123** [comment]
even on my local network i cannot connect to my xbox. I have not tested cloud yet.
