### ISSUE TITLE
stuck on connecting to console

### ISSUE THREAD

**Issue by humza2000** [unknownskl/xbox-xcloud-client#949]
works on the same network as the xbox (series x) but otherwise it gets stuck on the "connecting to console" part. i am on an m2 macbook

**Comment by moisesbelda** [comment]
For me it is failing since beta9, and if I shutdown the client 1 or 2 times, and start the connection again, it works.
Take a look : #950

**Comment by BenTheMan69** [comment]
I have this exact same problem! Has anyone gotten a solution?

**Comment by ivan-gaydamakin** [comment]
same v1.2.0 via Windows

**Comment by infyplay** [comment]
all work 14 beta i connected xbox x and s fine connecting

**Comment by unknownskl** [comment]
v2.0.0-beta14 should fix this issue. If you are still experiencing issues then please report them in #896

**Comment by Anaythesteve123** [comment]
still not working for me :(

**Comment by ghost** [comment]
Tested on 2.2.1 on steam deck and M1 Pro MacBook and still getting infinite 'connecting to console' :(
