### ISSUE TITLE
Issue connecting to xbox series x locally not working since beta9

### ISSUE THREAD

**Issue by moisesbelda** [unknownskl/xbox-xcloud-client#950]
Steps to reproduce:
- Xbox Series X 
- Steam Deck. It happens since version beta9,10,...12. (beta8 works correctly)
- Click on connect to xbox after the xbox is in sleep mode, and it is always stucked on  loading. Meanwhile xbox seems that is wake up, since I can hear the "startup" sound inside... but the client is not connected.
- After this initial try, sometimes if  I shutdown the client one or two times,  it finally connects to the xbox instantly, but in other tries, it never works. If I connect through official client (ios) and come back to greenlight, it finally connects.

Thanks

**Comment by SK-Crow** [comment]
Same issue here, but Windows 10.  I can connect normally with the standard Xbox app, but greenlight just spins.  If I relaunch 5-10 times it'll connect.  Seems to have only started a few days ago.

**Comment by moisesbelda** [comment]
have you tried with differents versions of the client? beta8, beta9, beta12?

**Comment by unknownskl** [comment]
New 2.0.0-beta14 should resolve the issue. If you still experience issue then please report in #896

**Comment by Anaythesteve123** [comment]
still not working for me :(
