### ISSUE TITLE
Beta 14 Stream error result: Failed

### ISSUE THREAD

**Issue by SK-Crow** [unknownskl/xbox-xcloud-client#957]
Stream error result: Failed
Details: [WNSError] Xccs : ErrorCallingWNS : Send command failed : State WaitingForServerToRegister

![image](https://github.com/unknownskl/greenlight/assets/1341176/e085c975-470c-4983-8128-92c87adf56b3)

Beta 14.  Error is displayed when attempting to connect to console to stream.  Beta 12 and 13 did not give this result.

**Comment by J0E6469** [comment]
I, too, have the same error. I'm running macOS Ventura 13.5.2. My issue was resolved after rebooting my XBOX.

**Comment by unknownskl** [comment]
Sometimes the xbox will lose connection to the xbox servers and then this error pops up. A restart of the xbox should resolve the issue.
