### ISSUE TITLE
Mouse support for games

### ISSUE THREAD

**Issue by TrackTechMediaGroup** [unknownskl/xbox-xcloud-client#960]
Would love to see mouse support for games, and not just Microsoft Edge.

**Comment by unknownskl** [comment]
There is already mouse and keyboard support for Mouse and Keyboard. You can enable this in the settings under 'Inputs'. Make sure to both select the new gamepad driver and mouse and keyboard. It works best when streaming from your home console and be cautious that it may still be very experimental and things are still being worked on so make sure to be prepared for that.
