### ISSUE TITLE
Xbox controller 

### ISSUE THREAD

**Issue by Ardnevad** [unknownskl/xbox-xcloud-client#970]
After I updated to Beta14 my Xbox controller no longer works correctly.

The buttons seem to be mapped weird and checked setting local on the Xbox and on the steam deck but, everything looks mapped right.

**Comment by Kobi-Blade** [comment]
This is not an issue with Greenlight, is an issue with Xbox itself, and affects even the Official App.

**Comment by Ardnevad** [comment]
I have gone back to beta13 and it works fine and back to beta14 and its mapping is off

**Comment by Kobi-Blade** [comment]
As stated, [[1](https://www.reddit.com/r/FortNiteBR/comments/121w08n/controller_doesnt_function_properly_when_xbox/)].

Known issue for over a year with XBox when connected through remote play, unrelated to Greenlight.

**Comment by Ardnevad** [comment]
So going back and forth from versions one work one doesn't, it it's an Xbox issue, ok thanks.
