### ISSUE TITLE
Bug: Unable to connect to console 

### ISSUE THREAD

**Issue by TrackTechMediaGroup** [unknownskl/xbox-xcloud-client#979]
Haven't done anything with the app or console since last night when it worked
![Screenshot 2023-10-04 at 19 16 10 1](https://github.com/unknownskl/greenlight/assets/120676221/6af988f9-d1cb-4c88-8f4b-d3d0ff537d4a)

**Comment by faithguy19** [comment]
Same is happening to me. Made no changes.

**Comment by unknownskl** [comment]
Restart your xbox. The console sometimes loses connection to the xbox network and fails to connect because of this.
