### ISSUE TITLE
This and the player projects are missing license

### ISSUE THREAD

**Issue by lostmsu** [unknownskl/xbox-xcloud-client#992]

**Comment by gunnaraas** [comment]
Greenlight had MIT License previously (see: #141 ) but seemingly was removed later. 

@unknownskl can you clarify how this software can be used & restore the appropriate license file? I am interested in helping make Greenlight easier for Steam Deck users by making it available to install via KDE Discover and/or Steam, but it is unclear if this type of redistribution is permitted without this information & your consent.

**Comment by unknownskl** [comment]
I've added a license file.
Regarding the publication of the software on stores it is fine by me, however i really do strongly prefer to receive a pull request / some information on how to publish the software to the stores in a automated manner. That way we can push out updates much quicker and doesn't rely on a 3rd party to maintain the releases.
